

services:
  calculator:
    image: ghcr.io/marielly-garcia-jimenez/desarrollo-web-3/backend_app:latest
    pull_policy: always
    container_name: practicas-calculator-1
    volumes:
      - ./backend:/app
    environment:
      MONGO_URL: mongodb://admin_user:web3@practicas-mongo-1:27017/?authSource=admin
    ports:
      - "8089:8000"
    networks:
      - mongo-network
    restart: always

  frontend:
    image: ghcr.io/marielly-garcia-jimenez/desarrollo-web-3/frontend_app:latest
    pull_policy: always
    container_name: practicas-frontend-1
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - calculator
    networks:
      - mongo-network
    restart: always

networks:
  mongo-network:
    driver: bridge
